---
- name: Build docker image & deploy on docker container
  gather_facts: true
  hosts: localhost
  tasks:
    - name: Build the image on local
      docker_image:
       name: BharatIMA/abc-technology
       source: build
       build:
        path: .
       tag: latest
    - name: Log into DockerHub
      docker_login:
       username: BharatIMA
       password: DevOps12
       email: ersingh302@gmail.com
    - name: Tag and push to docker hub on local
      docker_image:
       name: BharatIMA/abc-technology:latest
       repository: BharatIMA/abc-technology
       push: yes
       source: local
    - name: Remove image
      ignore_errors: yes
      docker_image:
       state: absent
       name: BharatIMA/abc-technology
       tag: latest
    - name: Log into DockerHub
      docker_login:
       username: BharatIMA
       password: DevOps12
       email: ersingh302@gmail.com
    - name: Pull image from dockerhub repo
      docker_image:
       name: BharatIMA/abc-technology:latest
       source: pull
    - name: install Pod network
      become: yes
      become_user: jenkins
      shell: kubectl apply -f https://raw.githubusercontent.com/BharatIMA/abc-technologies/master/kube-deployment.yml
      args:
        chdir: $HOME
...
